// Frontend wiring: calls the bound Go App methods (from guiapi) over Wails.
//
// The imports below resolve to bindings GENERATED by the Wails toolchain into
// frontend/wailsjs/ on `wails dev` / `wails generate module`. They do not exist
// until then (the directory is gitignored), so type-checking this file requires
// running Wails once.
import { ListHosts, AddHost, RemoveHost } from "../wailsjs/go/guiapi/App";
import { hosts } from "../wailsjs/go/models";

const app = document.querySelector<HTMLDivElement>("#app")!;
app.innerHTML = `
  <h1>dnsctl — hosts</h1>
  <form id="add-form">
    <input id="hostname" placeholder="hostname (e.g. app.local)" required />
    <input id="ip" placeholder="IP (e.g. 127.0.0.1)" required />
    <input id="comment" placeholder="comment (optional)" />
    <button type="submit">Add</button>
  </form>
  <p id="error" style="color:#c00"></p>
  <table>
    <thead><tr><th>IP</th><th>Hostname</th><th>Comment</th><th></th></tr></thead>
    <tbody id="entries"></tbody>
  </table>
`;

const errorEl = document.querySelector<HTMLParagraphElement>("#error")!;
const tbody = document.querySelector<HTMLTableSectionElement>("#entries")!;

async function refresh(): Promise<void> {
  errorEl.textContent = "";
  const entries = await ListHosts();
  tbody.innerHTML = "";
  for (const e of entries) {
    const row = document.createElement("tr");
    row.innerHTML = `<td>${e.ip}</td><td>${e.hostname}</td><td>${e.comment ?? ""}</td>`;
    const cell = document.createElement("td");
    const btn = document.createElement("button");
    btn.textContent = "Remove";
    btn.addEventListener("click", async () => {
      await RemoveHost(e.hostname);
      await refresh();
    });
    cell.appendChild(btn);
    row.appendChild(cell);
    tbody.appendChild(row);
  }
}

document.querySelector<HTMLFormElement>("#add-form")!.addEventListener("submit", async (ev) => {
  ev.preventDefault();
  errorEl.textContent = "";
  const entry = new hosts.Entry({
    hostname: (document.querySelector<HTMLInputElement>("#hostname")!).value,
    ip: (document.querySelector<HTMLInputElement>("#ip")!).value,
    comment: (document.querySelector<HTMLInputElement>("#comment")!).value || undefined,
  });
  try {
    await AddHost(entry);
    (document.querySelector<HTMLFormElement>("#add-form")!).reset();
    await refresh();
  } catch (err) {
    // Errors from the Go layer (validation, helper not installed, etc.).
    errorEl.textContent = String(err);
  }
});

refresh().catch((err) => {
  errorEl.textContent = String(err);
});
