// Frontend wiring: calls the bound Go App methods (from guiapi) over Wails.
//
// The imports below resolve to bindings GENERATED by the Wails toolchain into
// frontend/wailsjs/ on `wails dev` / `wails generate module`. They do not exist
// until then (the directory is gitignored), so type-checking this file requires
// running Wails once.
import "./style.css";
import {
  DNSStatus,
  Backend,
  ListHosts,
  AddHost,
  RemoveHost,
} from "../wailsjs/go/guiapi/App";
import { hosts } from "../wailsjs/go/models";

// Mirrors guiapi.ServiceDNS. Typed locally so the read path doesn't depend on
// the generated model namespace.
interface ServiceDNS {
  service: string;
  servers: string[];
  dhcp: boolean;
  primary: boolean;
}

type View = "dns" | "hosts" | "settings";
type Theme = "light" | "dark" | "system";

// --- Theme ---

const THEME_KEY = "dnsctl.theme";

function getTheme(): Theme {
  const t = localStorage.getItem(THEME_KEY);
  return t === "light" || t === "dark" || t === "system" ? t : "system";
}

function applyTheme(theme: Theme): void {
  const root = document.documentElement;
  if (theme === "system") root.removeAttribute("data-theme");
  else root.setAttribute("data-theme", theme);
  localStorage.setItem(THEME_KEY, theme);
}

// --- Font ---

type Font = "system" | "rounded" | "mono";

const FONT_KEY = "dnsctl.font";

// CSS font stacks per option, used both for the live --ui-font and the preview
// tiles. Keep in sync with [data-font] rules in style.css.
const FONT_STACKS: Record<Font, string> = {
  system: `-apple-system, BlinkMacSystemFont, "SF Pro Text", "Helvetica Neue", sans-serif`,
  rounded: `ui-rounded, "SF Pro Rounded", -apple-system, system-ui, sans-serif`,
  mono: `ui-monospace, "SF Mono", Menlo, Monaco, monospace`,
};

function getFont(): Font {
  const f = localStorage.getItem(FONT_KEY);
  return f === "rounded" || f === "mono" ? f : "system";
}

function applyFont(font: Font): void {
  const root = document.documentElement;
  if (font === "system") root.removeAttribute("data-font");
  else root.setAttribute("data-font", font);
  localStorage.setItem(FONT_KEY, font);
}

// Apply before rendering to avoid a flash of the wrong palette/font.
applyTheme(getTheme());
applyFont(getFont());

const GEAR_SVG = `<svg viewBox="0 0 16 16" fill="currentColor" aria-hidden="true"><path d="M8 5a3 3 0 100 6 3 3 0 000-6zm0 1.5a1.5 1.5 0 110 3 1.5 1.5 0 010-3z"/><path d="M6.94 1.5a.9.9 0 01.9-.75h.32a.9.9 0 01.9.75l.12.74a4.6 4.6 0 011.06.61l.7-.28a.9.9 0 011.1.39l.16.28a.9.9 0 01-.2 1.15l-.58.47c.05.36.05.72 0 1.08l.58.47a.9.9 0 01.2 1.15l-.16.28a.9.9 0 01-1.1.39l-.7-.28c-.33.26-.69.46-1.06.61l-.12.74a.9.9 0 01-.9.75h-.32a.9.9 0 01-.9-.75l-.12-.74a4.6 4.6 0 01-1.06-.61l-.7.28a.9.9 0 01-1.1-.39l-.16-.28a.9.9 0 01.2-1.15l.58-.47a4.7 4.7 0 010-1.08l-.58-.47a.9.9 0 01-.2-1.15l.16-.28a.9.9 0 011.1-.39l.7.28c.33-.26.69-.46 1.06-.61l.12-.74z"/></svg>`;

const app = document.querySelector<HTMLDivElement>("#app")!;
app.innerHTML = `
  <aside class="sidebar">
    <div class="sidebar-title">dnsctl</div>
    <button class="nav-item" data-view="dns">DNS Status</button>
    <button class="nav-item" data-view="hosts">Hosts</button>
    <div class="sidebar-spacer"></div>
    <button class="nav-item icon-item" data-view="settings" title="Settings">${GEAR_SVG}Settings</button>
  </aside>
  <main class="content" id="content"></main>
`;

const content = document.querySelector<HTMLElement>("#content")!;
const navItems = Array.from(document.querySelectorAll<HTMLButtonElement>(".nav-item"));

function escapeHtml(s: string): string {
  return s.replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]!);
}

function setView(view: View): void {
  navItems.forEach((n) => n.classList.toggle("active", n.dataset.view === view));
  if (view === "dns") void renderDNS();
  else if (view === "hosts") void renderHosts();
  else renderSettings();
}
navItems.forEach((n) => n.addEventListener("click", () => setView(n.dataset.view as View)));

// --- DNS Status (read-only) ---

async function renderDNS(): Promise<void> {
  content.innerHTML = `<h1>DNS Status</h1><p class="subtitle">Loading…</p>`;
  try {
    const backend = await Backend();
    const rows = (await DNSStatus()) as unknown as ServiceDNS[];
    const list = rows
      .map(
        (r) => `
        <div class="row">
          <span class="primary">${escapeHtml(r.service)}</span>
          ${r.primary ? `<span class="badge active">Active</span>` : ``}
          <span class="spacer"></span>
          ${
            r.dhcp
              ? `<span class="badge">Automatic (DHCP)</span>`
              : `<span class="secondary mono">${r.servers.map(escapeHtml).join(", ")}</span>`
          }
        </div>`
      )
      .join("");
    content.innerHTML = `
      <h1>DNS Status</h1>
      <p class="subtitle">Read-only — current system resolver configuration via ${escapeHtml(backend)}</p>
      <div class="card">${list || `<div class="empty">No network services found.</div>`}</div>`;
  } catch (err) {
    content.innerHTML = `<h1>DNS Status</h1><p class="error">${escapeHtml(String(err))}</p>`;
  }
}

// --- Hosts (editable) ---

async function renderHosts(): Promise<void> {
  content.innerHTML = `
    <h1>Hosts</h1>
    <p class="subtitle">dnsctl-managed entries in /etc/hosts</p>
    <div class="toolbar">
      <input id="h-hostname" placeholder="hostname (app.local)" />
      <input id="h-ip" placeholder="IP (127.0.0.1)" />
      <input id="h-comment" placeholder="comment (optional)" />
      <button class="btn primary" id="h-add">Add</button>
    </div>
    <p class="error" id="h-error"></p>
    <div class="card" id="h-list"></div>`;
  document.querySelector<HTMLButtonElement>("#h-add")!.addEventListener("click", () => void addHost());
  await refreshHosts();
}

async function refreshHosts(): Promise<void> {
  const listEl = document.querySelector<HTMLDivElement>("#h-list")!;
  const entries = await ListHosts();
  if (!entries.length) {
    listEl.innerHTML = `<div class="empty">No managed entries yet.</div>`;
    return;
  }
  listEl.innerHTML = "";
  for (const e of entries) {
    const row = document.createElement("div");
    row.className = "row";
    row.innerHTML = `
      <span class="primary mono">${escapeHtml(e.hostname)}</span>
      <span class="secondary mono">${escapeHtml(e.ip)}</span>
      ${e.comment ? `<span class="badge">${escapeHtml(e.comment)}</span>` : ``}
      <span class="spacer"></span>`;
    const btn = document.createElement("button");
    btn.className = "btn danger";
    btn.textContent = "Remove";
    btn.addEventListener("click", async () => {
      await RemoveHost(e.hostname);
      await refreshHosts();
    });
    row.appendChild(btn);
    listEl.appendChild(row);
  }
}

async function addHost(): Promise<void> {
  const errEl = document.querySelector<HTMLParagraphElement>("#h-error")!;
  errEl.textContent = "";
  const hostname = document.querySelector<HTMLInputElement>("#h-hostname")!.value.trim();
  const ip = document.querySelector<HTMLInputElement>("#h-ip")!.value.trim();
  const comment = document.querySelector<HTMLInputElement>("#h-comment")!.value.trim();
  try {
    await AddHost(new hosts.Entry({ hostname, ip, comment: comment || undefined }));
    document.querySelector<HTMLInputElement>("#h-hostname")!.value = "";
    document.querySelector<HTMLInputElement>("#h-ip")!.value = "";
    document.querySelector<HTMLInputElement>("#h-comment")!.value = "";
    await refreshHosts();
  } catch (err) {
    // Errors from the Go layer (validation, helper not installed, etc.).
    errEl.textContent = String(err);
  }
}

// --- Settings ---

function renderSettings(): void {
  const currentTheme = getTheme();
  const currentFont = getFont();

  const themeOpt = (value: Theme, label: string) =>
    `<button data-theme="${value}" class="${value === currentTheme ? "active" : ""}">${label}</button>`;

  const fontTile = (value: Font, label: string) =>
    `<button class="font-tile ${value === currentFont ? "active" : ""}" data-font="${value}"
       style="font-family: ${FONT_STACKS[value]}">
       <div class="font-sample">Aa</div>
       <div class="font-sample-sub">127.0.0.1 · app.local</div>
       <div class="font-name">${label}</div>
     </button>`;

  content.innerHTML = `
    <h1>Settings</h1>
    <p class="subtitle">Preferences</p>
    <div class="card">
      <div class="row">
        <span class="primary">Appearance</span>
        <span class="secondary">Theme used by the dnsctl window</span>
        <span class="spacer"></span>
        <div class="segmented" id="theme-seg">
          ${themeOpt("light", "Light")}${themeOpt("dark", "Dark")}${themeOpt("system", "System")}
        </div>
      </div>
      <div class="field">
        <span class="field-label">Font</span>
        <div class="font-grid" id="font-grid">
          ${fontTile("system", "System")}${fontTile("rounded", "Rounded")}${fontTile("mono", "Mono")}
        </div>
      </div>
    </div>`;

  const seg = document.querySelector<HTMLDivElement>("#theme-seg")!;
  seg.querySelectorAll<HTMLButtonElement>("button").forEach((btn) => {
    btn.addEventListener("click", () => {
      applyTheme(btn.dataset.theme as Theme);
      seg.querySelectorAll("button").forEach((b) => b.classList.toggle("active", b === btn));
    });
  });

  const grid = document.querySelector<HTMLDivElement>("#font-grid")!;
  grid.querySelectorAll<HTMLButtonElement>(".font-tile").forEach((tile) => {
    tile.addEventListener("click", () => {
      applyFont(tile.dataset.font as Font);
      grid.querySelectorAll(".font-tile").forEach((t) => t.classList.toggle("active", t === tile));
    });
  });
}

setView("dns");
